#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := udp_server
IDF_PATH := /home/cullen/Documents/Software/esp-idf

include $(IDF_PATH)/make/project.mk

